osx_image: xcode7.3
language: objective-c
sudo: false
env:
  matrix:
      - DESTINATION="OS=8.4,name=iPhone 6"
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -workspace Buttons.xcworkspace -scheme Buttons -configuration Debug -sdk iphonesimulator -destination "$DESTINATION" test -enableCodeCoverage YES | xcpretty -tc
after_success:
  - bash <(curl -s https://codecov.io/bash)
